apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-secret-operator.fullname" . }}-config
  labels:
    {{- include "k8s-secret-operator.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
