apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "internal-secrets-operator.fullname" . }}-config
  labels:
    {{- include "internal-secrets-operator.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ toYaml .Values.config | indent 4 }}
